# fastlane/Fastfile

default_platform(:android)

platform :android do
  desc "Deploys a signed app bundle to the Google Play Internal track"
  lane :internal_testing do
    # Use the `supply` action to upload the AAB to the Play Store.
    # The `aab` path is relative to the workspace root, so we use `../`
    # as the GitHub Actions job `cd`s into the 'fastlane' directory.
    supply(
      aab: "/Users/macbookpro/Flutter/color_rash/build/app/outputs/bundle/prodRelease/app-prod-release.aab",
      package_name: "com.colorrash.color_rash",
      track: "internal",
      # `json_key` is the path to your service account key,
      # which is created by your GitHub Actions workflow.
      json_key: "google_play_key.json"
    )

    # Note: We are not running the build command here because it's already handled
    # by the `flutter build` step in your GitHub Actions workflow.
    # The responsibility of this Fastlane lane is only the deployment.
  end
end