# fastlane/Gemfile

source "https://rubygems.org"

gem "fastlane"
gem "fastlane-plugin-email" # <--- ADD THIS LINE

# If you use `bundle exec`, you should run `bundle install`
# in your project's `fastlane` directory to generate the Gemfile.lock.