# .github/workflows/android_build.yml
name: Flutter Android Build & Deploy

on:
  push:
    branches: [ release ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy: # <--- NEW: A single job for both build and deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'

#      - name: Force time sync
#        run: sudo ntpdate pool.ntp.org
#        shell: bash

      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            ${{ runner.tool_cache }}/flutter
            ${{ runner.tool_cache }}/dart
            ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Setup .env.prod for Production Build
        run: |
          echo "${{ secrets.PROD_ENV_FILE_CONTENT }}" > .env.prod
          echo "Created .env.prod file from GitHub Secret."

      #      - name: Setup google-services.json for Production Build
      #        run: |
      #          echo "${{ secrets.GOOGLE_SERVICES_JSON_PROD }}" > android/app/google-services.json
      #          echo "Created google-services.json from GitHub Secret."



      # --- START of SIGNING STEPS ---
      # These steps decode the key from the GitHub Secret and create a properties file for Gradle
      - name: Decode Keystore File
        run: |
          echo "${{ secrets.UPLOAD_KEYSTORE }}" | base64 --decode > android/app/upload-keystore.jks


      - name: Create keystore.properties file
        run: |
          echo "storeFile=upload-keystore.jks" >> android/key.properties
          echo "storePassword=${{ secrets.UPLOAD_KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.UPLOAD_KEY_ALIAS }}" >> android/key.properties
          echo "keyPassword=${{ secrets.UPLOAD_KEY_PASSWORD }}" >> android/key.properties
      # --- END of SIGNING STEPS ---

      - name: Build Android App Bundle
        run: flutter build appbundle --flavor prod --release

      # <--- NEW DEPLOYMENT STEPS: All in the same job now --->
      - name: Setup Ruby and Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true


      - name: Setup Google Play Credentials
        run: |
          mkdir -p fastlane
          echo "${{ secrets.GOOGLE_PLAY_KEY_JSON_BASE64 }}" | base64 --decode > fastlane/google_play_key.json
          echo "Google Play key file created."

      - name: Set up Fastlane Match (if used)
        # This is optional and for code signing, but is often part of a full Fastlane setup.
        # This step is a placeholder if you decide to use Fastlane Match later.
        run: echo "Skipping Fastlane Match for now."

      - name: Deploy to Google Play Internal Testing
        run: |
          cd fastlane
          bundle install # Install gems from the Gemfile
          bundle exec fastlane internal_testing
        env:
          # These environment variables are passed to the Fastlane process
          GOOGLE_PLAY_KEY_FILE: ${{ github.workspace }}/fastlane/google_play_key.json
          FLUTTER_ROOT: ${{ runner.tool_cache }}/flutter
          # Other environment variables as needed