# .github/workflows/android_build.yml
name: Flutter Android Build & Deploy

on:
  push:
    branches: [ release ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The "build" job remains the same, but we will make it output an artifact
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'

      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            ${{ runner.tool_cache }}/flutter
            ${{ runner.tool_cache }}/dart
            ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Setup .env.prod for Production Build
        run: |
          echo "${{ secrets.PROD_ENV_FILE_CONTENT }}" > .env.prod
          echo "Created .env.prod file from GitHub Secret."
        # This step should run BEFORE the build command.

      - name: Decode google-services.json
        # This step assumes google-services.json is part of your repo for simplicity.
        # If it's a secret, you would decode it here.
        run: echo "Skipping google-services.json decoding as it's assumed to be in repo."

      - name: Build Android App Bundle
        run: flutter build appbundle --flavor prod --release
        # Note: Your build.gradle must be configured to use your prod flavor's settings here.

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: color-rash-android-appbundle
          path: build/app/outputs/bundle/prodRelease/app-prod-release.aab # <--- Ensure this path is correct for your 'prod' flavor build
          # The path might vary. Check your build logs for the exact path.

  # <--- NEW JOB: The "deploy" job depends on the "build" job --->
  deploy:
    # This job will only run if the "build" job was successful
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code again in the deploy job
      - uses: actions/checkout@v4

      # Step 2: Download the artifact generated by the "build" job
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: color-rash-android-appbundle
          path: build/app/outputs/bundle/release/ # Download the artifact to this path

      # Step 3: Set up the Google Play credentials
      - name: Setup Google Play Credentials
        run: |
          echo "${{ secrets.GOOGLE_PLAY_JSON_KEY }}" > fastlane/google_play_key.json
          echo "Google Play key file created."

      # Step 4: Use Fastlane to deploy the app bundle to Google Play Store
      - name: Deploy to Google Play Internal Testing
        uses: fastlane/github-action@v2
        with:
          # The Fastfile is in the fastlane/ directory
          # We need to tell Fastlane where the AAB is located
          aab_path: 'app-release.aab' # <--- Correct path relative to the runner root
          # These parameters are now passed as environment variables to the Fastfile
          android_package_name: 'com.colorrash.color_rash' # <--- Pass package name
          android_track: 'internal'
          android_json_key: 'fastlane/google_play_key.json' # Path to credentials file

          # This command executes the 'internal_testing' lane in the Fastfile
          command: |
            bundle exec fastlane internal_testing aab_path:app-release.aab package_name:com.colorrash.color_rash track:internal json_key:fastlane/google_play_key.json
